### ISSUE TITLE
I can't get it to work

### ISSUE THREAD

**Issue by kikoptr** [marcopeocchi/communitybuilds-node#1]
I put the command "npm i communitybuilds-node" and create a .js file with the first example code. I tried directly to see if it gave error because of the APIKEY but it came out like this:

```
(node:24000) UnhandledPromiseRejectionWarning: #<Object>
(node:24000) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:24000) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
Then I tried to include the parameter and it came out like this:

```
internal/process/promises.js:194
        triggerUncaughtException(err, true /* fromPromise */);
        ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Object>".] {
  code: ←[32m'ERR_UNHANDLED_REJECTION'←[39m
}
```
I have tried both .js including the APIKEY but the result is the same.
Maybe I'm running it wrong from the start, I don't know. My .js file contains exactly one copy paste from 
```
const { inspect } = require("util")
const { CommunityBuilds } = require("communitybuilds-node")

// you must init the package with a google-console apikey
CommunityBuilds.init("your-api-key")

// promise based example
CommunityBuilds.pyro()
    .then(res => {
        const [amber] = res.data.filter(character => character.name === "amber")
        console.log(inspect(amber, { depth: null }))
    })

// async context example
async function cryoBuilds(){
    const { data } = await CommunityBuilds.cryo()
    console.log(data)
}

async function artifacts(){
    const { data } = await CommunityBuilds.artifacts()
    console.log(data)
}
```

Thanks.

**Comment by marcopiovanello** [comment]
Hi @kikoptr!
First of all if you have to provide a **valid** google spreadsheet API_KEY, [this guide](https://handsondataviz.org/google-sheets-api-key.html) gets you covered.

If you set anything that is not a google api key the program will just crash.

Lastly, I suggest you updating to the latest version `2.0.11` and try something that does not require an API_KEY such as **.artifacts()** or .catalyst() / .bow() / ... functions.

**Comment by kikoptr** [comment]
Hi @marcopeocchi 
Agreed. I have tried what you indicate with the API_KEY but I got the same result.
I have upgraded to version 2.0.11 and changed the test script to:
```
const { inspect } = require("util")
const { CommunityBuilds } = require("communitybuilds-node")

(async () => {
  const { data } = await CommunityBuilds.bows()
  console.log(inspect(data, { depth: null }))
})()
```
The same errors no longer appear, but others do:
```
communitybuilds-node\node_modules\communitybuilds-node\lib\core\retrieve.js:32
            ttl: config.cacheTTL ?? 1000 * 60,
                                  ^

SyntaxError: Unexpected token '?'
←[90m    at wrapSafe (internal/modules/cjs/loader.js:1070:16)←[39m
←[90m    at Module._compile (internal/modules/cjs/loader.js:1120:27)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:1000:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:899:14)←[39m
←[90m    at Module.require (internal/modules/cjs/loader.js:1042:19)←[39m
←[90m    at require (internal/modules/cjs/helpers.js:77:18)←[39m
    at Object.<anonymous> (F:\GenshinImpact\communitybuilds-node\node_modules\←[4mcommunitybuilds-node←[24m\lib\index.js:4:20)
←[90m    at Module._compile (internal/modules/cjs/loader.js:1156:30)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)←[39m

```
I am using Node v12.16.2, should I use a specific version?
Thanks!

**Comment by marcopiovanello** [comment]
Aaah i see... the nullish coalescing operator is supported from node 16. 
I suggest you tu upgrade to node 16.
If it's a problem tell me and I'll try to transpile the code to a javascript version supported by node 12.

**Comment by kikoptr** [comment]
Great, I got it to work. I'll tell you.
I installed the latest version for windows (Node.js v18.12.0) and tried the script I put before but it gave this error
```
(async () => {
^

TypeError: require(...) is not a function
    at Object.<anonymous> ←[90m(F:\GenshinImpact\communitybuilds-node\←[39mtest.js:4:1←[90m)←[39m
←[90m    at Module._compile (node:internal/modules/cjs/loader:1159:14)←[39m
←[90m    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)←[39m
←[90m    at Module.load (node:internal/modules/cjs/loader:1037:32)←[39m
←[90m    at Module._load (node:internal/modules/cjs/loader:878:12)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)←[39m
←[90m    at node:internal/main/run_main_module:23:47←[39m

```
Adding ";" at the end of the line solved it.
`const { CommunityBuilds } = require("communitybuilds-node");`

I don't quite understand why this line needed the ";" and the other one didn't.

Finally, I tried again the example that uses the API_KEY (without adding the ";" to the require) and it worked fine :)

Thank you very much!

**Comment by marcopiovanello** [comment]
Javascript's ASI does not work well with IIFE. I suggest to put either a semicolon on the require statement or after the async block.
Or directly chage the IIFE block with something like 

```js
async function main(){
 ... your code ...
}

main()
```

Anyway, I'm glad that with node 18 it works.
